In [1]:
# Imports
import vugrad as vg
import numpy as np

In [2]:
# Recreating computation graph of q5
"""
A -> v
    <+> -> C
B -> ^
"""

a = vg.TensorNode(np.random.randn(2, 2))
b = vg.TensorNode(np.random.randn(2, 2))

c = a + b

In [13]:
print(f"A:\n{a.value}\n\nB:\n{b.value}\n")
print(f"C:\n{c.value}\n")
print(f"Source of C:\n{c.source}\n")
print(f"Source input 0:\n{c.source.inputs[0].value}\n")
print(f"A grad:\n{a.grad}\n")

A:
[[-0.39787767  0.765867  ]
 [ 0.65218538 -0.69540241]]

B:
[[-0.16033434  0.67655609]
 [-0.38214213  0.24437311]]

C:
[[-0.55821201  1.44242309]
 [ 0.27004325 -0.4510293 ]]

Source of C:

Source input 0:
[[-0.39787767  0.765867  ]
 [ 0.65218538 -0.69540241]]

A grad:
[[0. 0.]
 [0. 0.]]



# Q5

## What does c.value contain?
c.value contains the resulting array of the sum of TensorNode A and B, this operation is done elementwise.

## What does c.source refer to?
c.source refers to the OpNode (operation node) that created the TensorNode C. In this case it is a sum operation node, which contains the inputs A and B.

## What does c.source.inputs[0].value refer to?
c.source.inputs[0].value refers to the value of the first input of the sources, so the input of the operation node that resulted in node C is A and B, taking the first index refers to input A, taking its value shows that the same value as node A.

## What does a.grad refer to? What is its current value?
a.grad refers to the gradients of node A, this is currently all 0 as there has not been a backwards pass yet.